version: '3.8'

services:
  tf-jupyter:
    build:
      context: ./api-tf
      dockerfile: Dockerfile
      target: jupyter-runner
    container_name: pds-tf-jup
    image: pds-tf-jup:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - PORT=8888
    user: root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: ["gpu"]
    ports:
      - "10672:8888"
    volumes:
      - ./api-tf/workspace:/app/workspace
      - ./api-tf/.hf-cache:/usr/.hf-cache
    networks:
      - park
networks:
  park:
    external: true