version: '3.8'

services:
  # OLLAMA API
  ollama-api:
    container_name: pds-ollama
    build:
      context: ./api-ollama
      dockerfile: Dockerfile
    image: pds-ollama:latest
    ports:
      - "10669:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=1m
    volumes:
      - ./api-ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [ "gpu" ]
    networks:
      - park

  # OCR API
  ocr-api:
    container_name: pds-ocr
    image: pds-ocr:latest
    build:
      context: ./api-ocr
      dockerfile: Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "10671:5000"
    volumes:
      - ./api-ocr/assets:/app/assets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [ gpu ]
    networks:
      - park
networks:
  park:
    external: true