import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import clsx from "clsx";

import "./globals.css";
import { Providers } from "@/libs/provider";

const font = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="ko">
      <body
        className={clsx("bg-background antialiased", font.className)}
        style={{ minHeight: "100dvh" }}
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
