import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import clsx from "clsx";

import "./globals.css";
import { Providers } from "@/libs/provider";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const font = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="ko">
      <body
        className={clsx("bg-background antialiased", font.className)}
        style={{ minHeight: "100dvh" }}
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
          <Header />
          <div className="flex flex-start items-start w-full h-[calc(100vh - 52px)]">
            <Sidebar />
            <div className="flex-1 h-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
